version: '3'
services:
  splogger:
    container_name: splogger
    build:
      context: .
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
